[[repos]]
repo = "builtin"
hooks = [
  { id = "trailing-whitespace" },
  { id = "check-added-large-files" },
  { id = "check-case-conflict" },
  { id = "check-illegal-windows-names" },
  { id = "end-of-file-fixer" },
  { id = "check-json" },
  { id = "check-yaml" },
  { id = "check-toml" },
  { id = "check-xml" },
  { id = "check-vcs-permalinks" },
  { id = "mixed-line-ending" },
  { id = "check-symlinks" },
  { id = "destroyed-symlinks" },
  { id = "check-merge-conflict" },
  { id = "detect-private-key" },
  { id = "check-executables-have-shebangs" },
  { id = "check-shebang-scripts-are-executable" },
  { id = "no-commit-to-branch", args = ["--branch", "main"] },
]

[[repos]]
repo = "local"

[[repos.hooks]]
id = "ruff-check"
name = "ruff check"
language = "system"
entry = "uv run --group lint ruff check --fix"
pass_filenames = false
always_run = true

[[repos.hooks]]
id = "ruff-format"
name = "ruff format"
language = "system"
entry = "uv run --group lint ruff format"
pass_filenames = false
always_run = true

[[repos.hooks]]
id = "ty-check"
name = "ty check"
language = "system"
entry = "uv run --group qa ty check"
pass_filenames = false
always_run = true
